BasicEshop/BasicEshop/Models/Forms/SearchForm.cs
using System.ComponentModel.DataAnnotations;

namespace BasicEshop.Models.Forms
{
    public class SearchForm
    {
        [Display(Name = "Search")] [Required] public string Search { get; set; }
    }
}

BasicEshop/BasicEshop/Controllers/BlogController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using BasicEshop.Models;
using BasicEshop.Models.Database;
using BasicEshop.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BasicEshop.Controllers
{
    public class BlogController : BaseController
    {
        private DatabaseContext _context;

        public BlogController(DatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            var articles = _context.Articles
                .Include(article => article.FeaturedImage)
                .Include(article => article.User.Customer)
                .Where(article => article.PublishedAt != null)
                .Where(article => article.PublishedAt < DateTime.Now)
                .OrderByDescending(article => article.PublishedAt);
            ViewBag.Articles = await PaginatedList<Article>.CreateAsync(articles.AsNoTracking(), pageNumber);

            return View();
        }

        public IActionResult Detail(string articleUrl)
        {
            ViewBag.Article = _context.Articles
                .Include(article => article.FeaturedImage)
                .Include(article => article.User.Customer)
                .Include(article => article.Comments)
                .ThenInclude(comment => comment.User.Customer)
                .Where(article => article.PublishedAt < DateTime.Now)
                .Where(article => article.PublishedAt != null)
                .FirstOrDefault(article => article.Url == articleUrl);

            return View();
        }
    }
}

BasicEshop/BasicEshop/Controllers/ProductController.cs
using System.Linq;
using System.Threading.Tasks;
using BasicEshop.Models;
using BasicEshop.Models.Database;
using BasicEshop.Models.Entities;
using BasicEshop.Models.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BasicEshop.Controllers
{
    public class ProductController : BaseController
    {
        private DatabaseContext _context;

        public ProductController(DatabaseContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int pageNumber = 1, [FromQuery]ProductFilterForm productFilterForm = null)
        {
            IQueryable<Product> products = _context.Products
                .Include(x => x.Images)
                .ThenInclude(image => image.Image);

            if (productFilterForm.CategoryId != null)
            {
                products = products.Where(x => x.CategoryId == productFilterForm.CategoryId);
            }

            if (productFilterForm.SellerIds != null)
            {
                var sellerIds = productFilterForm.SellerIds.Split(",").ToList();
                products = products.Where(x => sellerIds.Contains(x.SellerId));
            }
            
            ViewBag.Products = await PaginatedList<Product>.CreateAsync(products.AsNoTracking(), pageNumber, 9);

            ViewBag.Categories = _context.Categories.Where(x => x.ParentId == null).ToList();
            ViewBag.Sellers = _context.Sellers.ToList();
            return View(productFilterForm);
        }

        public IActionResult? Search()
        {
            return null;
        }
    }
}

BasicEshop/BasicEshop/Views/Shared/ProductPreview.cshtml
@model BasicEshop.Models.Entities.Product


<div class="product-preview">
    <div class="product-preview-image">
        <img alt="@Model?.Title" src="@Model?.FeaturedImage?.FileName"/>
        @if (Model?.IsDiscounted == true)
        {
            <div class="product-preview-discount">
                -@((int) ((Model.PriceOld - Model.Price) / (Model.PriceOld / 100)))%
            </div>
        }
        @if (Model?.SpecialTag != null)
        {
            <div class="product-preview-special-tag">
                @Model.SpecialTag
            </div>
        }
    </div>
    <div class="product-preview-info">
        <h6>@Model?.Title</h6>

        <div class="product-preview-price">
            <div class="product-preview-price-current">
                $@Model?.Price
            </div>
            @if (Model?.IsDiscounted == true)
            {
                <div class="product-preview-price-old">
                    $@Model?.PriceOld
                </div>
            }
        </div>
    </div>
</div>

BasicEshop/BasicEshop/Views/Shared/SearchForm.cshtml
@model BasicEshop.Models.Forms.SearchForm;

@using (Html.BeginForm("Search", "Product", FormMethod.Post))
{
    @Html.TextBoxFor(m => m.Search, new {@class = "form-control search-control", placeholder = "Search our store"})
}

BasicEshop/BasicEshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BasicEshop</title>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/all.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <div class="header-top">
        <div class="header-top-side container-fluid">
            <div class="header-socials">
                Follow Us:
                <ul>
                    <li>
                        <i class="fab fa-facebook-f"></i>
                    </li>
                    <li>
                        <i class="fab fa-twitter"></i>
                    </li>
                    <li>
                        <i class="fab fa-instagram"></i>
                    </li>
                    <li>
                        <i class="fab fa-youtube"></i>
                    </li>
                </ul>
            </div>
            <div class="header-my-account">
                My Account <i class="fas fa-angle-down"></i>
            </div>
        </div>
        <div class="header-top-main container-fluid">
            <img src="~/img/logo-white.png" alt="Logo" class="header-logo"/>
            <a class="header-cart">
                <div class="header-cart-inner">
                    <i class="fas fa-shopping-cart"></i>
                    <div class="header-cart-number">0</div>
                </div>
            </a>
            @* @{Html.RenderPartial("SearchForm");} *@
        </div>
    </div>
    <nav class="container-fluid">
        <ul>
            <li>
                <a asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li>
                <a asp-controller="Product" asp-action="Index">Products</a>
            </li>
            <li>
                <a asp-controller="Blog" asp-action="Index">Blog</a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="AboutUs">About</a>
            </li>
            <li>
                <a asp-controller="" asp-action="">Contact</a>
            </li>
        </ul>
    </nav>
</header>
<section>
    @RenderBody()
</section>


<footer>
    <div class="container-fluid">
        <div class="footer-top">
            <div class="row">
                <div class="col-12 col-xl-4">
                    <img src="~/img/logo.png" alt="Logo" class="footer-logo"/>
                    <p>
                        <span class="font-weight-bold">Address:</span><br/>
                        4710-4890 Breckinridge St, UK Burlington, VT 05401
                    </p>
                    <p>
                        <span class="font-weight-bold">Need Help?</span><br/>
                        Call: 1-800-345-6789
                    </p>
                    <p>
                        <span class="font-weight-bold">Email:</span><br/>
                        example@example.com
                    </p>

                </div>
                <div class="col-12 col-xl-2">
                    <h5>About US</h5>
                    <ul>
                        <li>
                            <a>About us</a>
                        </li>
                        <li>
                            <a>About us</a>
                        </li>
                        <li>
                            <a>About us</a>
                        </li>
                        <li>
                            <a>About us</a>
                        </li>
                    </ul>
                </div>
                <div class="col-12 col-xl-2">
                    <h5>Usefull Links</h5>
                    <ul>
                        <li>
                            <a>About us</a>
                        </li>
                        <li>
                            <a>About us</a>
                        </li>
                        <li>
                            <a>About us</a>
                        </li>
                        <li>
                            <a>About us</a>
                        </li>
                    </ul>
                </div>

                <div class="col-12 col-xl-4">
                    <h5>Latest Blogs</h5>

                </div>
            </div>
        </div>
        <div class="footer-bottom">
            Copyright © Vesoz All Right Reserved.
        </div>
    </div>
</footer>
@RenderSection("Scripts", false)
</body>
</html>